#!/bin/bash
# dmenu2 on AUR using i3-dmenu-desktop --dmenu option
# dmenu_run -nb "#1f222d" -sb "#1f222d" -sf "#7780a1" -fn "Noto Sans-12"  -b -h 25 -x 129 -y 1 -w 730
# dmenu_run -nb "#1f222d" -sb "#D5D5D5" -sf "#1f222d" -fn "Noto Sans-12"  -b -h 24 -x 170 -y 1 -w 600

dmenu_run -b -nb "#1f222d" -nf "#eff0eb" -sb "#D5D5D5" -sf "#1f222d" -fn "Liberation Mono-12" -w 600 -h 26 -x 170 -y 1